# Read the Docs configuration file for Sphinx projects
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  python:
    version: 3.12
    install:
      - requirements: docs/_ext/djangodummy/requirements.txt
sphinx:
  configuration: docs/conf.py
